# Build the manager binary
FROM golang:1.13.4 as builder

WORKDIR /dns-challenger

# Copy the go source
COPY dns-challenger/ .

RUN ls
# Fetch dependencies
RUN go mod download

# Build
RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 GO111MODULE=on go build -a -o dns-challenger ./cmd/server/main.go

# Use distroless as minimal base image to package the manager binary
# Refer to https://github.com/GoogleContainerTools/distroless for more details
FROM gcr.io/distroless/static:latest
WORKDIR /
COPY --from=builder /dns-challenger .
ENTRYPOINT ["/dns-challenger"]