apiVersion: v1
kind: Secret
metadata:
  name: {{ include "dns-challenger.fullname" . }}
  labels:
    app: {{ include "dns-challenger.name" . }}
    chart: {{ include "dns-challenger.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
type: Opaque
data:
  gcloud-dns-admin.json: {{ default "" .Values.gcloud.saJSON }}
